packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

catalog:
  '@cloudflare/workers-types': ^4.20260621.1
  '@orpc/client': ^1.13.14
  '@orpc/openapi': ^1.13.14
  '@orpc/server': ^1.13.14
  '@orpc/zod': ^1.13.14
  '@types/node': ^26.0.0
  alchemy: ^0.93.12
  dotenv: ^17.2.2
  hono: ^4.12.27
  typescript: 6.0.3
  zod: ^4.1.13
